import {
  Waves,
  Dumbbell,
  ConciergeBell,
  Car,
  Martini,
  Sparkles,
  Clapperboard,
  Wine,
  Cpu,
  Trees,
  BedDouble,
  Sun,
  Anchor,
  Coffee,
  Zap,
  Flower2,
  Users,
  ShieldCheck,
  type LucideIcon,
} from 'lucide-react'

const MAP: Record<string, LucideIcon> = {
  'Infinity Pool': Waves,
  'Private Pool': Waves,
  'Rooftop Pool': Waves,
  'Pool Deck': Waves,
  'Private Gym': Dumbbell,
  Gym: Dumbbell,
  Concierge: ConciergeBell,
  'Valet Parking': Car,
  Valet: Car,
  'Sky Lounge': Martini,
  Spa: Sparkles,
  'Wellness Spa': Sparkles,
  'Home Theater': Clapperboard,
  Cinema: Clapperboard,
  'Wine Cellar': Wine,
  'Smart Home': Cpu,
  'Home Automation': Cpu,
  Garden: Trees,
  'Sky Garden': Trees,
  'Guest Suite': BedDouble,
  'Staff Suite': BedDouble,
  'Private Terrace': Sun,
  'Pool Deck ': Sun,
  'Marina Access': Anchor,
  'Beach Club': Anchor,
  'Private Elevator': Zap,
  'EV Charging': Zap,
  'Co-work Lounge': Coffee,
  Cafe: Coffee,
  'Yoga Studio': Flower2,
  'Tennis Court': Users,
  'Motor Court': Car,
}

export function getAmenityIcon(name: string): LucideIcon {
  return MAP[name] ?? ShieldCheck
}
